version: "2"
services:
  web:
    image: nicola24/reviews
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URL: mongodb://ec2-54-183-10-86.us-west-1.compute.amazonaws.com/restaurants_reviews
      REDIS_HOST: redis
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  redis:
    image: redis:latest
    ports:
        - "6379:6379"
